# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_value.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_value.proto',
  package='get_value',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0fget_value.proto\x12\tget_value\"+\n\x0cValueRequest\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\"\x1b\n\nValueReply\x12\r\n\x05value\x18\x01 \x01(\t2D\n\x04Main\x12<\n\x08GetValue\x12\x17.get_value.ValueRequest\x1a\x15.get_value.ValueReply\"\x00\x62\x06proto3'
)




_VALUEREQUEST = _descriptor.Descriptor(
  name='ValueRequest',
  full_name='get_value.ValueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='get_value.ValueRequest.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='get_value.ValueRequest.size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=73,
)


_VALUEREPLY = _descriptor.Descriptor(
  name='ValueReply',
  full_name='get_value.ValueReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='get_value.ValueReply.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['ValueRequest'] = _VALUEREQUEST
DESCRIPTOR.message_types_by_name['ValueReply'] = _VALUEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ValueRequest = _reflection.GeneratedProtocolMessageType('ValueRequest', (_message.Message,), {
  'DESCRIPTOR' : _VALUEREQUEST,
  '__module__' : 'get_value_pb2'
  # @@protoc_insertion_point(class_scope:get_value.ValueRequest)
  })
_sym_db.RegisterMessage(ValueRequest)

ValueReply = _reflection.GeneratedProtocolMessageType('ValueReply', (_message.Message,), {
  'DESCRIPTOR' : _VALUEREPLY,
  '__module__' : 'get_value_pb2'
  # @@protoc_insertion_point(class_scope:get_value.ValueReply)
  })
_sym_db.RegisterMessage(ValueReply)



_MAIN = _descriptor.ServiceDescriptor(
  name='Main',
  full_name='get_value.Main',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=104,
  serialized_end=172,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetValue',
    full_name='get_value.Main.GetValue',
    index=0,
    containing_service=None,
    input_type=_VALUEREQUEST,
    output_type=_VALUEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAIN)

DESCRIPTOR.services_by_name['Main'] = _MAIN

# @@protoc_insertion_point(module_scope)
