# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import get_value_pb2 as get__value__pb2


class MainStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetValue = channel.unary_unary(
        '/get_value.Main/GetValue',
        request_serializer=get__value__pb2.ValueRequest.SerializeToString,
        response_deserializer=get__value__pb2.ValueReply.FromString,
        )


class MainServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetValue(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MainServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetValue': grpc.unary_unary_rpc_method_handler(
          servicer.GetValue,
          request_deserializer=get__value__pb2.ValueRequest.FromString,
          response_serializer=get__value__pb2.ValueReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'get_value.Main', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
